Q_and_A = [
    ["1. What is the capital city of Australia?", ["a) Sydney", "b) Melbourne", "c) Canberra", "d) Brisbane"], "c) Canberra"],
    ["2. Who wrote the play 'Romeo and Juliet'?", ["a) Charles Dickens", "b) William Shakespeare", "c) Jane Austen", "d) Mark Twain"], "b) William Shakespeare"],
    ["3. What is the largest mammal on Earth?", ["a) Elephant", "b) Blue Whale", "c) Giraffe", "d) Gorilla"], "b) Blue Whale"],
    ["4. In which year did the first moon landing occur?", ["a) 1965", "b) 1969", "c) 1972", "d) 1975"], "b) 1969"],
    ["5. What is the currency of Japan?", ["a) Yen", "b) Won", "c) Ringgit", "d) Baht"], "a) Yen"],
    ["6. Who painted the Mona Lisa?", ["a) Vincent van Gogh", "b) Leonardo da Vinci", "c) Pablo Picasso", "d) Michelangelo"], "b) Leonardo da Vinci"],
    ["7. What is the largest planet in our solar system?", ["a) Mars", "b) Jupiter", "c) Saturn", "d) Earth"], "b) Jupiter"],
    ["8. Which continent is known as the 'Land Down Under'?", ["a) Europe", "b) South America", "c) Australia", "d) Africa"], "c) Australia"],
    ["9. Who was the first President of the United States?", ["a) Thomas Jefferson", "b) George Washington", "c) John Adams", "d) Abraham Lincoln"], "b) George Washington"],
    ["10. What is the chemical symbol for gold?", ["a) Gd", "b) Au", "c) Ag", "d) Fe"], "b) Au"],
    ["11. In which year did the Titanic sink?", ["a) 1905", "b) 1912", "c) 1920", "d) 1931"], "b) 1912"],
    ["12. Which planet is known as the 'Red Planet'?", ["a) Venus", "b) Mars", "c) Jupiter", "d) Saturn"], "b) Mars"],
    ["13. What is the world's largest ocean?", ["a) Atlantic Ocean", "b) Indian Ocean", "c) Southern Ocean", "d) Pacific Ocean"], "d) Pacific Ocean"],
    ["14. Who wrote the 'Harry Potter' book series?", ["a) J.R.R. Tolkien", "b) J.K. Rowling", "c) George R.R. Martin", "d) Suzanne Collins"], "b) J.K. Rowling"],
    ["15. What is the longest river in the world?", ["a) Nile", "b) Amazon", "c) Yangtze", "d) Mississippi"], "a) Nile"],
    ["16. Who is known as the father of modern physics?", ["a) Isaac Newton", "b) Albert Einstein", "c) Galileo Galilei", "d) Nikola Tesla"], "b) Albert Einstein"],
    ["17. What is the chemical symbol for water?", ["a) H2O", "b) CO2", "c) NaCl", "d) O2"], "a) H2O"],
    ["18. Which famous scientist invented the telephone?", ["a) Alexander Graham Bell", "b) Thomas Edison", "c) Nikola Tesla", "d) Guglielmo Marconi"], "a) Alexander Graham Bell"],
    ["19. What is the hardest natural substance on Earth?", ["a) Gold", "b) Diamond", "c) Quartz", "d) Tungsten"], "b) Diamond"],
    ["20. Who wrote the novel 'To Kill a Mockingbird'?", ["a) Harper Lee", "b) J.D. Salinger", "c) F. Scott Fitzgerald", "d) Ernest Hemingway"], "a) Harper Lee"],
    ["21. What is the chemical symbol for oxygen?", ["a) O", "b) Ox", "c) Oxg", "d) O2"], "a) O"],
    ["22. Which planet is known as the 'Morning Star' or 'Evening Star'?", ["a) Venus", "b) Mercury", "c) Mars", "d) Jupiter"], "a) Venus"],
    ["23. What is the currency of China?", ["a) Yen", "b) Won", "c) Renminbi", "d) Yuan"], "c) Renminbi"],
    ["24. Who is the author of 'The Great Gatsby'?", ["a) Ernest Hemingway", "b) F. Scott Fitzgerald", "c) Harper Lee", "d) Mark Twain"], "b) F. Scott Fitzgerald"],
    ["25. What is the largest organ in the human body?", ["a) Liver", "b) Brain", "c) Skin", "d) Heart"], "c) Skin"],
    ["26. In which year did World War I begin?", ["a) 1905", "b) 1914", "c) 1918", "d) 1939"], "b) 1914"],
    ["27. Who painted 'Starry Night'?", ["a) Claude Monet", "b) Vincent van Gogh", "c) Pablo Picasso", "d) Leonardo da Vinci"], "b) Vincent van Gogh"],
    ["28. What is the chemical symbol for silver?", ["a) Ag", "b) Si", "c) S", "d) Au"], "a) Ag"],
    ["29. Which country is known as the 'Land of the Rising Sun'?", ["a) China", "b) Japan", "c) South Korea", "d) Thailand"], "b) Japan"],
    ["30. Who is the author of '1984'?", ["a) George Orwell", "b) Aldous Huxley", "c) J.R.R. Tolkien", "d) H.G. Wells"], "a) George Orwell"]
]
